<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427664-->
<messages>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>72</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> attribute name "Ã1/2" (value="xx") is invalid]]></text>
  </message>
  <message>
    <code>59</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> unexpected or duplicate quote mark]]></text>
  </message>
  <message>
    <code>59</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> unexpected or duplicate quote mark]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> attribute "width" has invalid value "align="""]]></text>
  </message>
  <message>
    <code>53</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> proprietary attribute "width"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Document content looks like HTML Proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, 0 errors were found!
]]></text>
  </message>
</messages>
