<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427818-->
<messages>
  <message>
    <code>65</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<a> discarding newline in URI reference]]></text>
  </message>
  <message>
    <code>58</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<a> attribute with missing trailing quote mark]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>110</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Doctype given is "-//W3C//DTD HTML 3.2//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, 0 errors were found!
]]></text>
  </message>
  <message>
    <code>81</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[URIs must be properly escaped, they must not contain unescaped
characters below U+0021 including the space character and not
above U+007E. Tidy escapes the URI for you as recommended by
HTML 4.01 section B.2.1 and XML 1.0 section 4.2.2. Some user agents
use another algorithm to escape such URIs and some server-sided
scripts depend on that. If you want to depend on that, you must
escape the URI by your own. For more information please refer to
http://www.w3.org/International/O-URL-and-ident.html
]]></text>
  </message>
</messages>
