<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 431716-->
<messages>
  <message>
    <code>110</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Document content looks like HTML 4.01 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[No system identifier in emitted doctype]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[No warnings or errors were found.
]]></text>
  </message>
</messages>
