<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 443362-->
<messages>
  <message>
    <code>8</code>
    <level>2</level>
    <line>26</line>
    <column>11</column>
    <text><![CDATA[discarding unexpected <!DOCTYPE>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Doctype given is "-//W3C//DTD XHTML 1.0 Strict//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[1 warning, 0 errors were found!
]]></text>
  </message>
</messages>
