<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 532535-->
<messages>
  <message>
    <code>21</code>
    <level>2</level>
    <line>7</line>
    <column>57</column>
    <text><![CDATA[<o:p> is not approved by W3C]]></text>
  </message>
  <message>
    <code>110</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Document content looks like HTML Proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[1 warning, 0 errors were found!
]]></text>
  </message>
</messages>
