<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 539369a-->
<messages>
  <message>
    <code>7</code>
    <level>2</level>
    <line>13</line>
    <column>1</column>
    <text><![CDATA[missing </noframes> before <frameset>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>15</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected </noframes>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>18</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected </frame>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>20</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected </html>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>8</line>
    <column>1</column>
    <text><![CDATA[missing </frameset>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>13</line>
    <column>1</column>
    <text><![CDATA[trimming empty <noframes>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>14</line>
    <column>9</column>
    <text><![CDATA[trimming empty <frameset>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Doctype given is "-//W3C//DTD HTML 4.0 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>1</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Document content looks like HTML 4.01 Frameset]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[7 warnings, 0 errors were found!
]]></text>
  </message>
</messages>
